### ISSUE TITLE
Minimum Android version

### ISSUE THREAD

**Issue by iampato** [diepnghitinh/christian_picker_image#16]
`use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 21,`

Change to 16

**Comment by shengbiaoguo** [comment]
me too,  minSdk of at most 16.

**Comment by Iampato** [comment]
[https://github.com/diepnghitinh/christian_picker_image/pull/17](https://github.com/diepnghitinh/christian_picker_image/pull/17)
made a pull request lets see ....
