### ISSUE TITLE
Getting error after doing flutter pub get

### ISSUE THREAD

**Issue by LaxmikanthMadhyastha** [diepnghitinh/christian_picker_image#2]
After adding package to the pubspec.yaml and doing flutter pug bet results in below error

```Couldn't read file LocalFile: '/Users/7sugar/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/christian_picker_image-0.1.0/android/src/main/kotlin/com/christian/christian_picker_image/ChristianPickerImagePlugin.kt' even though it exists. Please verify that this file has read permission and try again```

**Comment by diepnghitinh** [comment]
True path is christian_picker_image-0.1.0/android/src/main/java/com/christian/christian_picker_image/ChristianPickerImagePlugin.kt , not  .../kotlin/com/...
Try with https://stackoverflow.com/questions/58579774/convert-an-existing-flutter-kotlin-project-to-flutter-java-project

**Comment by badboy-tian** [comment]
+1

**Comment by badboy-tian** [comment]
other plugin no this error. just some plugin

**Comment by simkepal** [comment]
Hey, I also get an error when trying to add the plugin. 

Couldn't read file Instance of 'ErrorHandlingFile' even though it exists. Please verify that this file has read permission and try again.

Is there solution for this?

**Comment by Ahmadre** [comment]
Fix is there: https://github.com/diepnghitinh/christian_picker_image/pull/3

We just have to wait until the author will check my PR

**Comment by diepnghitinh** [comment]
hi everyone, I have just updated a new version for the library.
- Update miss file on kotlin based project.
pubspec.yaml
christian_picker_image: ^0.1.1

**Comment by simkepal** [comment]
Hey, thanks!

Now I get another error:

`Using software rendering with device Android SDK built for x86. You may get better performance with hardware mode by configuring hardware rendering for your device.
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Kotlin plugin should be enabled before 'kotlin-android-extensions'

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/simonpal/.pub-cache/hosted/pub.dartlang.org/christian_picker_image-0.1.1/android/build.gradle' line: 70

* What went wrong:
A problem occurred evaluating project ':christian_picker_image'.
> Could not get unknown property 'supportLibraryVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 636ms
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         1.3s
Gradle task assembleDebug failed with exit code 1`

**Comment by diepnghitinh** [comment]
> Hey, thanks!
> 
> Now I get another error:
> 
> `Using software rendering with device Android SDK built for x86. You may get better performance with hardware mode by configuring hardware rendering for your device.
> Launching lib/main.dart on Android SDK built for x86 in debug mode...
> Kotlin plugin should be enabled before 'kotlin-android-extensions'
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file '/Users/simonpal/.pub-cache/hosted/pub.dartlang.org/christian_picker_image-0.1.1/android/build.gradle' line: 70
> * What went wrong:
>   A problem occurred evaluating project ':christian_picker_image'.
> 
> > Could not get unknown property 'supportLibraryVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 636ms
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done 1.3s
> Gradle task assembleDebug failed with exit code 1`

#1
