### ISSUE TITLE
Build error on new build system

### ISSUE THREAD

**Issue by nothinggift** [diepnghitinh/christian_picker_image#20]
> error: Unexpected duplicate tasks:
    1) Target 'christian_picker_image' (project 'Pods') has copy command from '/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/christian_picker_image-0.1.6/ios/Classes/ImagePicker/Images/selectedImageGallery@3x.png' to '/Users/builder/clone/build/ios/Debug-iphoneos/christian_picker_image/christian_picker_image.framework/selectedImageGallery@3x.png'
    2) Target 'christian_picker_image' (project 'Pods') has copy command from '/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/christian_picker_image-0.1.6/ios/Classes/ImagePicker/Images/selectedImageGallery@3x.png' to '/Users/builder/clone/build/ios/Debug-iphoneos/christian_picker_image/christian_picker_image.framework/selectedImageGallery@3x.png'
    error: Unexpected duplicate tasks:

Legacy Build System works well.

**Comment by jamesdhope** [comment]
same issue. Legacy Build Systems works. Removing the PNG files from the POD file / compiled sources within XCode also seems to temporarily resolve the issue.

**Comment by luis-cruzt** [comment]
I'm still having this issue, any fix?
Changing to Legacy Build is not solving my problem, i only get more errors.

**Comment by oncul** [comment]
same problem i cannot fix with legacy build.

**Comment by luis-cruzt** [comment]
I think that @diepnghitinh has to fix this, but i think he is inactive.

**Comment by luis-cruzt** [comment]
I think i found the solution that works for me:

It would be great if you guys can test it and tell me if it works for you:
https://github.com/luis-cruzt/christian_picker_image/commit/b67fa0f069e0c310b7dd2a31f845a8005f213171
